name: Generic build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build free
      run: dotnet build -c Release src/SimpleS3.sln
    - name: Build commercial
      run: dotnet build -c CommercialRelease src/SimpleS3.sln