name: Nuget release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+**'

env:
  DOTNET_EnableDiagnostics: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'
      - name: Pack release
        run: dotnet pack -c Release -o tmp SimpleS3.sln
      - name: Upload to nuget
        run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json tmp/*