name: Nuget release

on:
  push:
    tags:
    - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Pack free release
      run: dotnet pack -c Release src/SimpleS3.sln -o Temp
    - name: Pack commercial release
      run: dotnet pack -c CommercialRelease src/SimpleS3.Commercial.sln -o Temp
    - name: Upload to nuget
      run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json Temp/*.nupkg